# Generated by Django 3.2.8 on 2021-10-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapId', models.CharField(max_length=20)),
                ('certificate1', models.FileField(upload_to='')),
                ('certificate2', models.FileField(upload_to='')),
            ],
        ),
    ]
