# Generated by Django 3.2.8 on 2021-10-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('sapId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Full_vaccinate', models.BooleanField()),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('DOB', models.DateField()),
            ],
        ),
    ]
