# Generated by Django 3.2.8 on 2021-10-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_app', '0002_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.RemoveField(
            model_name='details',
            name='DOB',
        ),
        migrations.AddField(
            model_name='details',
            name='certificate',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
