# Generated by Django 3.2.8 on 2021-10-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_app', '0003_auto_20211027_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Full_vaccinate',
            field=models.BooleanField(default=False),
        ),
    ]
