# Generated by Django 3.2.3 on 2021-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_app', '0004_alter_details_full_vaccinate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='Full_vaccinate',
            new_name='full_vaccinate',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='certificate',
        ),
        migrations.AddField(
            model_name='details',
            name='department',
            field=models.CharField(default='IT', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='year',
            field=models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='FE', max_length=5),
            preserve_default=False,
        ),
    ]
