# Generated by Django 3.2.3 on 2021-11-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_app', '0005_auto_20211108_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='folder_id',
            field=models.CharField(default='none', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10),
        ),
    ]
